### ISSUE TITLE
Raspberry Pi 3/4 Slower than realtime - Input Overflowed while running test_microphone.py 

### ISSUE THREAD

**Issue by valkyreee** [alphacep/vosk-api#326] opened 2020-12-20 19:18 UTC
OSError: [Errno -9981] Input overflowed

here is some info on the USB microphone i use:
{'index': 0, 
'structVersion': 2, 
'name': 'USB PnP Sound Device: Audio (hw:2,0)', 
'hostApi': 0, 
'maxInputChannels': 1, 
'maxOutputChannels': 0, 
'defaultLowInputLatency': 0.008684807256235827, 
'defaultLowOutputLatency': -1.0, 
'defaultHighInputLatency': 0.034829931972789115, 
'defaultHighOutputLatency': -1.0,
 'defaultSampleRate': 44100.0}

**Comment by nshmyrev** [comment] 2020-12-24 18:04
I investigated it a bit:

RPi CPU sucks, painfully slow, even my Xiaomi Redmi 4x is faster
Openblas on ARM sucks a lot, need to move to Xiaomi Mace or similar things.
Openfst also sucks, very slow
Recording must be in own thread

Overall, a lot of work ahead.

**Comment by nshmyrev** [comment] 2021-01-04 23:45
Some more details after investigation:

1. Overall matrix computation is slow, we can probably reduce matrix sizes to make it smaller. Last layer is the most expensive (192 x 2192 x 8 frames)
2. Clang is much faster than GCC (1.5x). Flags for RPI3 recommended in the net are wrong, the right ones are `-mcpu=cortex-a15 -mfpu=neon`
2. Blasefeo library is amazing due to panel matrix packing, 3 times faster than openblas on Android. Not so straightforward to integrate into Kaldi though, needs more work.
3. On RPI3 integers are very slow, slower than floats. I havent' found good matrix library for in16, maybe there will be something for int8. In general quantization requires int8 it seems.

**Comment by nshmyrev** [comment] 2021-01-07 23:38
With version 0.3.16 we got 30% speedup for vosk, please test. I still have to play with the microphone.

**Comment by mi-hol** [comment] 2021-01-08 09:14
@nshmyrev I'm confused because the issue title reference RPI model 4 but your comment reference RPI3.
Do the improvements apply for RPI4?

**Comment by nshmyrev** [comment] 2021-01-08 09:38
> Do the improvements apply for RPI4?

Yes

**Comment by RafNie** [comment] 2021-01-09 17:50
Hi @nshmyrev 
I can not find build for arm6l since release 0.3.16. Are last Raspberry related improvements compilable for this architecture?

**Comment by nshmyrev** [comment] 2021-01-09 18:45
> I can not find build for arm6l since release 0.3.16. Are last Raspberry related improvements compilable for this architecture?

For which device do you need arm6l? Zero is too slow

**Comment by RafNie** [comment] 2021-01-09 19:34
Offline decoding is possible on Pi zero. But I rather curious how your improvements affects online decoding with really small G and dictionary. I know that is still lot of computations in AM part, so most probably online will not be possible.I dream about small voice controlled devices on zero 🙂

**Comment by nshmyrev** [comment] 2021-01-09 22:19
The problem is that I have to rebuild toolchain for gcc 8 for armv6, its a bit painful. I decided to focus on rpi3.

I have just pushed microphone update https://github.com/alphacep/vosk-api/commit/6f2d6d0d69faacf3c9183818635cecca18ad6a97 with proper queue and proper sound library (sounddevice instead of pyaudio). 

Now it works ok, I'll close this one.

**Closed as completed by nshmyrev** 2021-01-09 22:19 UTC
