### ISSUE TITLE
Cannot build on Linux (Debian 10)

### ISSUE THREAD

**Issue by FBorgeat** [alphacep/vosk-api#14] opened 2020-01-13 22:17 UTC
Trying to build on Linux and I get this error, I am on the latest Gradle available:

![](https://sourceforge.net/p/cmusphinx/discussion/help/thread/9acbd2f3/380a/d860/2385/1dc6/a829/attachment/image.png)

**Comment by nshmyrev** [comment] 2020-01-13 22:18
Hi 

Like message says, please update gradle. You can get it from gradle website https://gradle.org/install/ or you can edit graddle-wrapper.properties, like message says.

**Comment by FBorgeat** [comment] 2020-01-14 01:40
The file mentioned in the message does not exist, found out sudo apt-get upgrade does not upgrade to latest version, upgraded gradle from the url you provided but gradle -v still returns 5.2.1, trying to solve that, sorry I am very new to Linux.

**Comment by FBorgeat** [comment] 2020-01-14 02:23
I have solved my gradle issue, but now running 'gradle build' returns this: 
![image](https://user-images.githubusercontent.com/41712432/72308489-a1e76e00-364a-11ea-884b-3f17a16165a5.png)

if i run './build-kaldi.sh' i get this:
![image](https://user-images.githubusercontent.com/41712432/72308659-e3781900-364a-11ea-8581-6a1f018bb290.png)

**Comment by nshmyrev** [comment] 2020-01-14 07:55
Please check the corresponding folder, why it doesn't exist. Maybe you do not have ndk fully installed.

**Comment by vrillco** [comment] 2020-01-15 04:37
This is caused by the variable ANDROID_NDK_HOME being hardcoded in build-kaldi.sh.  I got around it by commenting that line out, and defining it as an environment variable that matches the NDK path on my own machine.

Another hardcoded path is PROJECT_ROOT in CMakeLists.txt.  I replaced it with `"${PROJECT_SOURCE_DIR}/.."`

**Comment by nshmyrev** [comment] 2020-01-19 19:31
Fixed now, thank you Bill!

**Closed as completed by nshmyrev** 2020-01-19 19:31 UTC
